export type IndustrySeed = { code: string; nameRu: string; nameKk?: string };

// Registry of future verticals. Only dentistry-kz is active until its
// taxonomy, compliance rules, suppliers and UI are certified.
export const industryCatalog: IndustrySeed[] = [
  ["dentistry-kz", "Стоматология"],
  ["beauty-kz", "Beauty и салоны красоты"],
  ["cosmetology-kz", "Косметология"],
  ["hair-kz", "Парикмахерские и барбершопы"],
  ["nail-kz", "Nail-индустрия"],
  ["lash-brow-kz", "Lash и brow-студии"],
  ["spa-wellness-kz", "SPA и wellness"],
  ["veterinary-kz", "Ветеринария"],
  ["medical-clinics-kz", "Медицинские клиники"],
  ["laboratories-kz", "Лаборатории и диагностика"],
  ["rehabilitation-kz", "Реабилитация и физиотерапия"],
  ["pharma-kz", "Аптеки и фармдистрибуция"],
  ["optics-kz", "Оптика"],
  ["horeca-kz", "HoReCa"],
  ["catering-kz", "Кейтеринг"],
  ["grocery-retail-kz", "Продуктовый ритейл"],
  ["bakery-kz", "Пекарни и кондитерские"],
  ["cleaning-kz", "Клининговые компании"],
  ["facility-management-kz", "Facility management"],
  ["office-procurement-kz", "Офисы и корпоративные закупки"],
  ["education-kz", "Образовательные учреждения"],
  ["kindergarten-kz", "Детские сады"],
  ["fitness-kz", "Фитнес-клубы"],
  ["sports-kz", "Спортивные центры"],
  ["construction-kz", "Строительство"],
  ["renovation-kz", "Ремонт и отделочные материалы"],
  ["professional-tools-kz", "Профессиональный инструмент"],
  ["industrial-supply-kz", "Снабжение производств"],
  ["industrial-equipment-kz", "Промышленное оборудование"],
  ["electrical-automation-kz", "Электрика и автоматизация"],
  ["plumbing-engineering-kz", "Сантехника и инженерные системы"],
  ["agriculture-kz", "Сельское хозяйство"],
  ["farms-kz", "Фермерские хозяйства"],
  ["greenhouses-kz", "Теплицы и агротехнологии"],
  ["farm-veterinary-kz", "Ветеринария для хозяйств"],
  ["auto-service-kz", "Автосервисы и СТО"],
  ["auto-parts-kz", "Автозапчасти"],
  ["tires-fluids-kz", "Шины, масла и технические жидкости"],
  ["logistics-kz", "Логистика и склады"],
  ["packaging-kz", "Упаковка и тара"],
  ["printing-advertising-kz", "Типографии и рекламные агентства"],
  ["textile-workwear-kz", "Текстиль и спецодежда"],
  ["occupational-safety-kz", "Охрана труда и безопасность"],
  ["security-services-kz", "Охранные предприятия"],
  ["it-office-tech-kz", "IT и офисная техника"],
  ["telecom-kz", "Телекоммуникации"],
  ["energy-kz", "Энергетика"],
  ["mining-kz", "Добывающие предприятия"],
  ["oil-gas-kz", "Нефтегазовый сектор"],
  ["chemical-kz", "Химическая промышленность"],
  ["laboratory-equipment-kz", "Лабораторное оборудование"],
  ["hvac-kz", "Климатическое оборудование"],
  ["water-treatment-kz", "Водоснабжение и водоочистка"],
  ["cleaning-equipment-kz", "Уборочная техника"],
  ["retail-equipment-kz", "Торговое оборудование"],
  ["refrigeration-kz", "Холодильное оборудование"],
  ["restaurant-equipment-kz", "Ресторанное оборудование"],
  ["business-furniture-kz", "Мебель для бизнеса"],
  ["hotel-supply-kz", "Отельное оснащение"],
  ["floristry-kz", "Флористика"],
  ["events-kz", "Организация мероприятий"],
  ["travel-kz", "Туристический бизнес"],
  ["real-estate-kz", "Агентства недвижимости"],
  ["property-management-kz", "Управляющие компании"],
  ["public-sector-kz", "Государственные учреждения"],
  ["nonprofit-kz", "Некоммерческие организации"],
  ["corporate-gifts-kz", "Корпоративные подарки"],
  ["stationery-kz", "Канцелярия и товары для офиса"],
  ["professional-printing-kz", "Печать и расходные материалы"],
  ["uniform-kz", "Униформа"],
  ["food-production-kz", "Пищевая промышленность"],
  ["meat-processing-kz", "Мясопереработка"],
  ["dairy-production-kz", "Молочное производство"],
  ["fish-production-kz", "Рыбное производство"],
  ["pharma-production-kz", "Фармацевтическое производство"],
  ["packaging-production-kz", "Производство упаковки"],
  ["furniture-production-kz", "Мебельное производство"],
  ["metalworking-kz", "Металлообработка"],
  ["woodworking-kz", "Деревообработка"],
].map(([code, nameRu]) => ({ code, nameRu, nameKk: nameRu }));
