import Image from "next/image";

const clinicBenefits = ["Сравнение цены за базовую единицу", "Актуальные остатки и сроки поставки", "Бюджеты, согласования и повтор закупки", "Документы и уведомления в одном контуре"];
const supplierBenefits = ["Единая витрина предложений и остатков", "Импорт из CSV, API, ERP и 1С-контура", "Акции, промокоды и аналитика продаж", "Юридический доступ после договора с ЭЦП"];

export default function LandingPage() {
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "DentMarket KZ", applicationCategory: "BusinessApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "KZT", description: "Пилотный доступ" }, areaServed: { "@type": "Country", name: "Kazakhstan" } };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="topbar"><a className="brand" href="#top" aria-label="DentMarket KZ — на главную"><span>DM</span><strong>DentMarket <small>KZ</small></strong></a><nav aria-label="Навигация"><a href="#clinics">Клиникам</a><a href="#suppliers">Поставщикам</a><a href="#process">Как работает</a><a href="#faq">FAQ</a></nav><a className="login" href="/register" data-event="header-login">Регистрация</a></header>
    <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">B2B-закупки для стоматологии</p><h1>Материалы приходят вовремя. Цены — без тумана.</h1><p className="lead">DentMarket объединяет клиники и проверенных поставщиков Казахстана: от поиска и сравнения до заказа, документов и контроля исполнения.</p><div className="heroActions"><a className="primary" href="/register?role=buyer" data-event="hero-clinic">Зарегистрировать клинику</a><a className="secondary" href="/register?role=supplier" data-event="hero-supplier">Я поставщик</a></div><div className="trust"><span><b>5</b> поставщиков в пилоте</span><span><b>ЭЦП</b> договор и документы</span><span><b>KZT</b> расчёты и локальная география</span></div></div><div className="heroVisual"><Image src="/dental-procurement-hero.png" alt="Стоматологические материалы и инструменты для закупки" fill priority sizes="(max-width: 900px) 100vw, 52vw" /></div></section>
    <section className="proof" aria-label="Ключевые возможности"><p>Каталог без дублей</p><p>Цена за штуку и упаковку</p><p>Остатки с контролем свежести</p><p>Split-заказ по поставщикам</p><p>Комплаенс и аудит</p></section>
    <section className="audience" id="clinics"><div className="sectionIntro"><p className="eyebrow">Для клиник</p><h2>Закупка перестаёт быть цепочкой звонков</h2><p>Сравнивайте эквивалентные предложения, управляйте лимитами и возвращайтесь к регулярным спискам без ручного восстановления заказа.</p></div><div className="featureGrid">{clinicBenefits.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>{["Система нормализует фасовку и показывает сопоставимую стоимость.", "Публикация зависит от свежести цены и доступного количества.", "Центры затрат и лимиты делают расход предсказуемым.", "Спецификации, счета, подписи и статусы доступны из заказа."][index]}</p></article>)}</div></section>
    <section className="supplierSection" id="suppliers"><div className="supplierPanel"><div><p className="eyebrow">Для поставщиков</p><h2>Один операционный канал вместо разрозненных заявок</h2><p>Загружайте ассортимент удобным способом, подтверждайте заказы и следите за качеством данных, выплатами и спросом.</p><a className="lightButton" href="/register?role=supplier" data-event="supplier-cta">Стать поставщиком</a></div><ol>{supplierBenefits.map((item) => <li key={item}>{item}</li>)}</ol></div></section>
    <section className="process" id="process"><div className="sectionIntro"><p className="eyebrow">От поиска до поставки</p><h2>Одна прозрачная цепочка</h2></div><div className="steps"><article><b>01</b><h3>Найдите</h3><p>Поиск по названию, бренду, характеристикам и категории.</p></article><article><b>02</b><h3>Сравните</h3><p>Цена, фасовка, остаток, доставка и подтверждение поставщика.</p></article><article><b>03</b><h3>Оформите</h3><p>Корзина разделится по поставщикам с неизменяемым снимком условий.</p></article><article><b>04</b><h3>Контролируйте</h3><p>Оплата, отгрузка, возвраты, документы и аудит в единой истории.</p></article></div></section>
    <section className="legal"><div><p className="eyebrow">Юридический контур</p><h2>Договор подписывается только тогда, когда нужен</h2></div><p>Поставщик и оператор подписывают договор двумя проверенными ЭЦП. Он действует 12 месяцев и продлевается ежегодно. Пока активный договор существует, повторное окно подписи недоступно; новая подпись потребуется при завершении договора или обязательном изменении условий.</p></section>
    <section className="faq" id="faq"><div className="sectionIntro"><p className="eyebrow">Вопросы</p><h2>Коротко о запуске</h2></div><div>{[["Кто может покупать?","Юридические лица и организации стоматологического профиля после регистрации и настройки ролей."],["Как проверяются поставщики?","Профиль, реквизиты, разрешительные документы и правила комплаенса проходят проверку до коммерческих операций."],["Можно ли интегрировать учётную систему?","Да. Архитектура поддерживает CSV, API, ERP/1С-адаптеры и входящие webhooks с подписью и защитой от повторов."],["Как работает договор с ЭЦП?","Обе стороны подписывают неизменяемую версию документа. После двух валидных ЭЦП договор активируется на год и открывает коммерческие операции."],["Есть ли плата за пилот?","Пилотный тариф заведён без списаний; коммерческие планы и лимиты управляются через биллинг и feature flags."]].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="finalCta"><p className="eyebrow">Начните с пилота</p><h2>Соберите закупки и продажи в одном профессиональном контуре</h2><div><a className="primary" href="/register?role=buyer" data-event="final-clinic">Зарегистрировать клинику</a><a className="secondary" href="/register?role=supplier" data-event="final-supplier">Стать поставщиком</a></div></section>
    <footer><a className="brand" href="#top"><span>DM</span><strong>DentMarket <small>KZ</small></strong></a><p>Пилотная B2B-платформа для стоматологического рынка Казахстана. · <a href="/legal/terms">Условия</a> · <a href="/legal/privacy">Конфиденциальность</a></p><p>© 2026 DentMarket KZ</p></footer>
  </main>;
}
