import Image from "next/image";

const clinicBenefits = ["Сравнение цены за базовую единицу", "Актуальные остатки и сроки поставки", "Бюджеты, согласования и повторные закупки", "Документы и уведомления по заказу"];
const supplierBenefits = ["Предложения, цены и остатки в одном кабинете", "Загрузка прайсов и подключение учётной системы", "Акции, промокоды и аналитика продаж", "Продажи после проверки и подписания договора"];
const buyerAppUrl = process.env.NEXT_PUBLIC_BUYER_APP_URL ?? "https://dentmarket-shop.vercel.app";
const supplierAppUrl = process.env.NEXT_PUBLIC_SUPPLIER_APP_URL ?? "https://dentmarket-supplier.vercel.app";

export default function LandingPage() {
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "DentMarket KZ", applicationCategory: "BusinessApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "KZT", description: "Пилотный доступ" }, areaServed: { "@type": "Country", name: "Kazakhstan" } };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="topbar"><a className="brand" href="#top" aria-label="DentMarket KZ, на главную"><span>DM</span><strong>DentMarket <small>KZ</small></strong></a><nav aria-label="Навигация"><a href="#clinics">Клиникам</a><a href="#suppliers">Поставщикам</a><a href="#process">Как работает</a><a href="#faq">Вопросы</a></nav><div className="headerActions"><a className="shopLink" href={buyerAppUrl} data-event="header-shop">В магазин</a><a className="login" href="/login" data-event="header-login">Войти</a></div></header>
    <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">Закупки для стоматологии</p><h1>Материалы, цены и сроки поставки в одном месте</h1><p className="lead">Сравнивайте предложения проверенных поставщиков Казахстана и оформляйте заказы с документами.</p><div className="heroActions"><a className="primary" href={buyerAppUrl} data-event="hero-shop">Перейти в магазин</a><a className="secondary" href="/register?role=buyer" data-event="hero-clinic">Зарегистрировать клинику</a><a className="textAction" href={supplierAppUrl} data-event="hero-supplier-cabinet">Кабинет поставщика →</a></div><div className="trust"><span><b>5</b> поставщиков в пилоте</span><span><b>ЭЦП</b> договор и документы</span><span><b>KZT</b> расчёты в тенге</span></div></div><div className="heroVisual"><Image src="/dental-procurement-hero.png" alt="Стоматологические материалы и инструменты для закупки" fill priority sizes="(max-width: 900px) 100vw, 52vw" /></div></section>
    <section className="proof" aria-label="Ключевые возможности"><p>Каталог без дублей</p><p>Цена за штуку и упаковку</p><p>Актуальные остатки</p><p>Заказы нескольким поставщикам</p><p>Проверка документов</p></section>
    <section className="audience" id="clinics"><div className="sectionIntro"><p className="eyebrow">Для клиник</p><h2>Закупка перестаёт быть цепочкой звонков</h2><p>Сравнивайте эквивалентные предложения, управляйте лимитами и возвращайтесь к регулярным спискам без ручного восстановления заказа.</p></div><div className="featureGrid">{clinicBenefits.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>{["Система нормализует фасовку и показывает сопоставимую стоимость.", "Публикация зависит от свежести цены и доступного количества.", "Центры затрат и лимиты делают расход предсказуемым.", "Спецификации, счета, подписи и статусы доступны из заказа."][index]}</p></article>)}</div><div className="sectionActions"><a className="primary" href={buyerAppUrl} data-event="clinic-shop">Открыть магазин</a><a className="secondary" href="/register?role=buyer">Создать аккаунт клиники</a></div></section>
    <section className="supplierSection" id="suppliers"><div className="supplierPanel"><div><p className="eyebrow">Для поставщиков</p><h2>Один операционный канал вместо разрозненных заявок</h2><p>Загружайте ассортимент удобным способом, подтверждайте заказы и следите за качеством данных, выплатами и спросом.</p><div className="supplierActions"><a className="lightButton" href={supplierAppUrl} data-event="supplier-cabinet">Открыть кабинет</a><a className="lightText" href="/register?role=supplier" data-event="supplier-cta">Стать поставщиком →</a></div></div><ol>{supplierBenefits.map((item) => <li key={item}>{item}</li>)}</ol></div></section>
    <section className="process" id="process"><div className="sectionIntro"><p className="eyebrow">От поиска до поставки</p><h2>Четыре понятных шага</h2></div><div className="steps"><article><b>01</b><h3>Найдите</h3><p>Ищите по названию, бренду, характеристикам или категории.</p></article><article><b>02</b><h3>Сравните</h3><p>Проверьте цену, фасовку, остаток и условия доставки.</p></article><article><b>03</b><h3>Оформите</h3><p>Корзина автоматически разделится на заказы поставщикам.</p></article><article><b>04</b><h3>Контролируйте</h3><p>Следите за оплатой, отгрузкой, возвратами и документами.</p></article></div></section>
    <section className="legal"><div><p className="eyebrow">Договор с поставщиком</p><h2>Подпись нужна один раз в год</h2></div><p>Поставщик и оператор подписывают одну версию договора с помощью ЭЦП. Повторная подпись потребуется после окончания срока или обязательного изменения условий.</p></section>
    <section className="faq" id="faq"><div className="sectionIntro"><p className="eyebrow">Вопросы</p><h2>Коротко о работе сервиса</h2></div><div>{[["Кто может покупать?","Клиники и другие организации стоматологического профиля после регистрации."],["Как проверяются поставщики?","До начала продаж мы проверяем профиль, реквизиты и обязательные документы поставщика."],["Можно ли подключить учётную систему?","Да. Можно загрузить прайс файлом или подключить 1С и другую учётную систему."],["Как работает договор с ЭЦП?","Поставщик и оператор подписывают одну версию договора. После двух действительных подписей поставщик получает доступ к продажам."],["Есть ли плата за пилот?","Нет. Во время пилота плата не списывается. Условия коммерческого запуска сообщим заранее."]].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="finalCta"><p className="eyebrow">Начните с пилота</p><h2>Управляйте закупками и продажами в DentMarket</h2><div><a className="primary" href={buyerAppUrl} data-event="final-shop">В магазин</a><a className="secondary" href="/register?role=buyer" data-event="final-clinic">Зарегистрировать клинику</a><a className="secondary" href={supplierAppUrl} data-event="final-supplier">Кабинет поставщика</a></div></section>
    <footer><a className="brand" href="#top"><span>DM</span><strong>DentMarket <small>KZ</small></strong></a><p>Пилотная платформа для стоматологического рынка Казахстана. <a href="/legal/terms">Условия</a> <a href="/legal/privacy">Конфиденциальность</a></p><p>© 2026 DentMarket KZ</p></footer>
  </main>;
}
